version: '2'
services:
    blogtest-app:
        image: blogtest
        external_links:
            - blogtest-postgresql:postgresql
            - blogtest-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/blogtest
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 8080:8080
    blogtest-postgresql:
        extends:
            file: postgresql.yml
            service: blogtest-postgresql
    blogtest-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: blogtest-elasticsearch
