version: '2'
services:
    blogtest-postgresql:
        container_name: blogtest-postgresql
        image: postgres:9.5.1
        # volumes:
        #     - ~/volumes/jhipster/blogtest/postgresql/:/var/lib/postgresql/
        environment:
            - POSTGRES_USER=blogtest
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
